### ISSUE TITLE
Automation script loaded failed.

### ISSUE THREAD

**Issue by zerodegress** [arch1t3cht/Aegisub#56] opened 2023-06-12 02:50 UTC
```
10:43:29: Multiple scripts in the Automation autoload directory failed to load.
Please review the errors, fix them and use the Rescan Autoload Dir button in Automation Manager to load the scripts again.
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\karaoke-auto-leadin.lua'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\kara-templater.lua'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\cleantags-autoload.lua'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\macro-1-edgeblur.lua'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\l0.DependencyControl.Toolbox.moon'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\select-overlaps.moon'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\macro-2-mkfullwitdh.lua'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\strip-tags.lua'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\cleantags-autoload.lua'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\l0.DependencyControl.Toolbox.moon'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\kara-templater.lua'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\macro-1-edgeblur.lua'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\karaoke-auto-leadin.lua'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\select-overlaps.moon'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\macro-2-mkfullwitdh.lua'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
10:43:29: 一个自动化脚本载入失败，文件名： '~\scoop\apps\aegisub-arch1t3cht\current\automation\autoload\strip-tags.lua'，错误报告：
 [string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
```
looks like that it uses my own lua installation,not its own.

**Comment by arch1t3cht** [comment] 2023-06-12 21:37
Can you give more details? What operating system are you using? How are you building/installing Aegisub?
It looks like you're using scoop in some way, which isn't really officially supported. If this is an issue with the scoop packaging (which I would suspect) instead of the upstream code, I might not really be able to help you, and this should be fixed in the respective scoop package instead.

**Comment by zerodegress** [comment] 2023-06-13 00:22
os: windows11
installing method: use the protable version and directly unzip it to use.
env:LUA_CPATH=~\scoop\apps\lua\current,LUA_EXE_PATH=~\scoop\apps\lua\current
I use my own scoop bucket to test installing it,here is it:https://github.com/zerodegress/zerobucket.
I have previously installed the lua and luarocks through scoop,it may overwrite some env variables,making the lua lib path wrong.
but after installing this aegisub version failed I tried to install official aegisub version through portable, and it works,maybe it is I had installed the aegisub thourgh the installer program.

**Comment by arch1t3cht** [comment] 2023-06-13 00:39
Then it seems like it was indeed an issue with your configuration.

**Closed by arch1t3cht** 2023-06-13 00:39 UTC

**Comment by Witchilich** [comment] 2023-11-23 16:15
> Then it seems like it was indeed an issue with your configuration.

Rather then his configuration, it seems to be due to the way scoop shims an app. Whether you install the portable or installer version (through Expand-InnoArchive or Expand-7zipArchive), the Aegisub shim will always seems to give the "Failed to load Automation Script" error.

The solution is to release the windows installer as exe without a zip archive. It could now be directly added to winget repo as arch1t3cht.Aegisub and arch1t3cht.Aegisub.wxMaster.

**Comment by brian6932** [comment] 2024-04-17 02:10
I also have this problem, if a specific lua version's required, it should be used and bundled. The official aegisub doesn't exhibit such a problem.
```
22:04:58: Multiple scripts in the Automation autoload directory failed to load.
Please review the errors, fix them and use the Rescan Autoload Dir button in Automation Manager to load the scripts again.
22:04:58: Failed to load Automation script '...\aegisub\automation\autoload\macro-1-edgeblur.lua':
[string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
22:04:58: Failed to load Automation script '...\aegisub\automation\autoload\macro-2-mkfullwitdh.lua':
[string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
22:04:58: Failed to load Automation script '...\aegisub\automation\autoload\kara-templater.lua':
[string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
22:04:58: Failed to load Automation script '...\aegisub\automation\autoload\l0.DependencyControl.Toolbox.moon':
[string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
22:04:58: Failed to load Automation script '...\aegisub\automation\autoload\select-overlaps.moon':
[string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
22:04:58: Failed to load Automation script '...\aegisub\automation\autoload\karaoke-auto-leadin.lua':
[string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
22:04:58: Failed to load Automation script '...\aegisub\automation\autoload\cleantags-autoload.lua':
[string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
22:04:58: Failed to load Automation script '...\aegisub\automation\autoload\strip-tags.lua':
[string "require('unicode-monkeypatch')"]:1: module 'unicode-monkeypatch' not found:
	no field package.preload['unicode-monkeypatch']
	no file '~\scoop\apps\lua\current'
```

**Comment by arch1t3cht** [comment] 2024-04-17 11:41
> If a specific lua version's required, it should be used and bundled.

And that is indeed what's being done on all releases.

As said above, whatever scoop package you are using is not maintained by me. This issue does not happen for the windows release bundles (nor for the CI artifacts), so it's an issue with this scoop port and should be reported there.

**Comment by brian6932** [comment] 2024-04-17 20:10
The scoop ports don't do anything outside of unzipping a portable install, I have the same issue on portable installs.

**Comment by arch1t3cht** [comment] 2024-04-17 20:23
Portable installs work fine on my end. Are you sure that your portable install is a completely clean one? Do you have any environment variables messing with the lua package path?

**Comment by brian6932** [comment] 2024-04-17 21:38
I do have a lua env var, same as the guy earlier, but that's a standard env var, if you have a portable install that requires specific deps, you need to either overwrite the env var or not read it at all, this isn't a user error.

**Comment by arch1t3cht** [comment] 2024-04-18 13:20
The package path is being overwritten here https://github.com/arch1t3cht/Aegisub/blob/91b198d12d44ab4c3d2489a74547c40993102f9a/libaegisub/lua/script_reader.cpp#L124-L141

I cannot reproduce your issue when setting LUA_PATH or LUA_CPATH environment variables (and according to the lua documentation, C modules are tried after lua modules so LUA_CPATH should not be relevant for finding lua modules).

If you have a scenario where a clean build (portable or otherwise) fails to start, I suggest you give a clear list of steps to reproduce on a clean install (in particular including your environment variables) instead of vague descriptions and condescending comments.
